agency/urls.py
from django.urls import path
 from . import views

app_name = 'agency'

urlpatterns = [
    path('agency' , views.agency , name = 'agency'),
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('' , views.home , name='home'),
]

bookstore/urls.py
from django.urls import path
from . import views

app_name = 'bookstore'

urlpatterns = [
    path('' , views.bookstore, name='bookstore'),
    path('logout', views.logout_view , name='logout'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('boards.urls')),
    path('news/', include('news.urls')),
    path('bookstore/' , include('bookstore.urls')),
] 
#+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views
app_name = 'news'
urlpatterns = [
    path('', views.news , name='news'),
    path('create/' , views.add_member  , name='greet'),
]

agency/models.py
from django.db import models
from django.utils import timezone

class Agency(models.Model):
    
    agency = models.CharField(max_length=100)
    added_on = models.DateTimeField(default=timezone.now)
    provide_haj = models.BooleanField(default=False , null=False)
    
    def __str__(self):
        return f'{self.agency} '
 

class Member(models.Model):
    member_name = models.CharField(max_length=100)
    agency_name = models.ManyToManyField(Agency)
    created_on = models.DateTimeField(default=timezone.now)
    
    
    def __str__(self):
        return f'{self.member_name}'

boards/models.py
from django.db import models


from django.contrib.auth.models import User

class Board(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255)
    
    def __str__(self):
        return f'{self.name}'
    

class Topic(models.Model):
    subject = models.CharField(max_length=255)
    board   = models.ForeignKey(Board , related_name='topics' , on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='topics', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.subject}'

class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic , related_name='posts', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='posts' , on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.message}'
       

bookstore/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from os import path , remove 
from random import sample


def upload_location(instance, filename):
	today = timezone.now()
	base , ext = path.splitext(filename)

	randomList = [
		'1','2','3','4','5','6','7','8','9','0','a','b','c','d','e','f',
		'g','h','i','j','k','l','m','n','o','p','q','r','s','t','u', 'w','x','y','z']
	rando = sample(randomList, 10)
	new_random = ''.join(rando).upper() 

	file_path = 'pictures/{date}-{basename}{filename}'.format(date=today, basename=new_random,  filename=ext)
	return file_path



class Bookstore(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    description =models.TextField()
    price = models.DecimalField( max_digits=7,  decimal_places=2)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)
    added_on = models.DateTimeField(default=timezone.now)
    picture = models.ImageField(upload_to=upload_location ,null=True , blank=True)
    
    def __str__(self):
        return f'{self.author} added this book {self.title}'
    

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Group(models.Model):
    group_name = models.CharField(max_length=255)
    group_admin = models.ForeignKey(User, on_delete=models.SET_NULL , null=True)
    creation_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(null=True)
    

    def __str__(self):
        return self.group_name 
    

class Group_member(models.Model):
    group_id = models.ForeignKey(Group , on_delete=models.CASCADE)
    joined_on = models.DateTimeField(default=timezone.now)
    member = models.ForeignKey(User , on_delete=models.CASCADE)
    
    def __str__(self):
        return f' {self.member} joined {self.group_id} '

agency/views.py
from django.shortcuts import render
from . models import Agency

def agency(request):
    
    context = {}
    return render(request, 'agency/agency.html' , context)

boards/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . models import Board , Post , Topic
from django.contrib.auth.models import User

def home(request):
    boards = Board.objects.all()
    context = {'boards': boards}
    #return HttpResponse('<h2>hello world </h2>')
    return render(request , 'boards/home.html' , context)

bookstore/views.py
from django.shortcuts import render
from .models import Bookstore
from django.contrib.auth import logout




def logout_view(request):
    logout(request)
    return render(request, 'boards/home.html')

def bookstore(request):
    books = Bookstore.objects.all().order_by('-added_on')
    
    
    context = {'books': books}
    for book in books:
        print(book.title)
        print(book.picture.url)
    
    
    return render(request , 'bookstore/bookstore.html' , context)

news/views.py
from django.shortcuts import render , redirect , get_object_or_404
from django.contrib.auth.models import User
from .models import Group  , Group_member
from django.http import HttpResponseRedirect



def greet(request):
    group= Group.objects.get(id=1)
    new_member = Group_member.objects.get()
    new = Group_member.objects.get
    print("created"  ,  group)
    
    
    
    
def add_member(request):
    members = Group_member.objects.filter(group_id=2).order_by('-id')
    context = {'members': members}
    
    if request.method == 'POST':
        user = request.user
        group = Group.objects.get(id=2)
        new = Group_member(group_id =group, member= user)
        new.save()
        return HttpResponseRedirect('/news/create/')
    else:
        return render(request, 'news/greet.html' , context )

    




def news(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']  
        user = User.objects.create_user( username=username, email=email , password=password , is_active=True , is_staff=True , is_superuser= True) 
        user.save()
        return redirect('/')    
    return render(request, 'news/news.html')

def news_detail(request, news_id):
    news_detail = get_object_or_404(Group , pk=news_id)
    context = {'news': news_detail}
    
    return render(request, 'news/detail.html'  , context)

boards/templates/boards/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>learn Python</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'css/style.css' %}">
    
</head>
<body>
    <section>
        <div class="left"></div>
        <div class="right">
       {% if user.is_authenticated %}
       <div>{{user.username|title}}</div>
       <div class="profile">
        <img class="profile-img" src="{% static 'img/user.png'  %}" alt="user-profile">
    </div>
       {% else %}
       <div>login</div>
       <div>sign up</div>
       {% endif %}
       
        </div>
    </section>
    <header>
        <div class="banner">
            <img  src="{% static 'img/eas.png' %}" alt="eas">
        </div>
    </header>
    <nav>
        <div>
            <a href="{% url 'news:news' %}">accueil</a>
        </div>
        <div>
            <a href="{% url 'bookstore:bookstore' %}">qui sommes nous </a>
        </div>
        <div>
            nos formations
        </div>
        <div>
           <a href="tel:0699776376">contactez-nous</a>
        </div>
        {% if  request.user.is_authenticated %}
        <div> <a href="{% url 'bookstore:logout' %}">logout </a> </div>

        {% else %}
        <div> <a href="{% url 'bookstore:logout' %}">login </a> </div>

        {% endif %}
    </nav>
    
    <article>
        {% for board in boards %}
       <h2>{{board.name|title}}</h2>
       <h3>{{board.description|title }}</h3>
        {% endfor %}
    </article>



    <footer>
        <h3>this is the footer of the website</h3>
    </footer>
    


    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

bookstore/templates/bookstore/bookstore.html
{%  load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>bookstore</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'css/bookstore.css'  %}">
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'css/media.css' %}">
    <script src='main.js'></script>
</head>
<body>
    <div class="container">
        {%  for book in books %}
        <div class="zone">
            <h2>{{book.title|title }}</h2>
            <h4>{{book.description }}</h4>           
           
            <h4>by {{book.added_by|title}}</h4>
        </div>

        {% endfor %}
        <div class="zone"></div>
        <div class="zone"></div>
        <div class="zone"></div>
        <div class="zone"></div>
        <div class="zone"></div>
        <div class="zone"></div>
        <div class="zone"></div>
        <div class="zone"></div>
        <div class="zone"></div>
        <div class="zone"></div>
        <div class="zone"></div>
        <div class="zone"></div>
        <div class="zone"></div>
        <div class="zone"></div>
        <div class="zone"></div>
        <div class="zone"></div>
        
        

    </div>
    

    
</body>
</html>

news/templates/news/detail.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>learn Django</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>
    
</body>
</html>

news/templates/news/greet.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    
</head>
<body>

    <form action="" method="post">
        {% csrf_token%}
        <button > greet</button>
    </form>
    <div>
        {% for member in members %}
       <p>{{ member.group_id }} <span>{{member.member}}</span></p>

        {% endfor %}
    </div>
    
</body>
</html>

news/templates/news/news.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>News Online</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'css/news.css' %}">
    
</head>
<body>
    <h1>welcoome to our news</h1>
    <div class="container">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/ly36kn0ug4k?si=0Km8h9myb7BOvdjU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    </div>
    <div style="font-size: 20px;">
        <pre>
            <code>
                let name = 'hakim';
                let age = 34;
                console.log(`Your name is ${name} and you are ${age});
            </code>
        </pre>
        <pre>
            <code>
                def name():
                    if name == 'hakim':
                        return True
                    else:
                        return False
    
            </code>
        </pre>
    </div>

    <section class="register">

        <form action="" method="post">
            {% csrf_token %}
            <input type="text" name="username" placeholder="username">
            <br>
            <input type="text" name="email" placeholder="email">
            <br>
            <input type="password" name="password" placeholder="password">
            <br>
            <input type="submit" value="Register">

        </form>
    </section>





    <script src="{% static 'js/news.css' %}"></script>
    
</body>
</html> 